name: Auto Scraper TMA Priok

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager pandas pytz openpyxl

      - name: Run Scraper
        run: python scraper_khusus.py 

      - name: Commit and Push
        run: |
          git config --global user.name "Bot-Stamar-Priok"
          git config --global user.email "bot@github.com"
          git add history_aws_priok.csv history_bpbd_pasarikan.csv
          git commit -m "Update data TMA [skip ci]" || exit 0
          git push origin main
