name: Auto Scraper TMA Priok

on:
  schedule:
    - cron: '*/15 * * * *' # Jalan otomatis tiap 15 menit
  workflow_dispatch: # Biar lu bisa klik "Run Workflow" manual kalau mau cek

permissions:
  contents: write

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ambil semua riwayat biar gak bentrok

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install selenium webdriver-manager pandas pytz openpyxl

      - name: Eksekusi Background Scraper
        run: python scraper_khusus.py 

      - name: Commit dan Push Hasil CSV ke Repo
        run: |
          git config --global user.name "Bot-Stamar-Priok"
          git config --global user.email "bot@github.com"
          
          # Daftarkan file CSV-nya secara spesifik
          git add history_aws_priok.csv history_bpbd_pasarikan.csv
          
          # Commit jika ada perubahan, kalau gak ada ya exit santai (exit 0)
          git commit -m "Auto-update data TMA [skip ci]" || exit 0
          
          # PAKSA PUSH (Force Push)
          # Ini obat terakhir buat ngatasi error 'rejected' selamanya
          git push origin main --force
